#!/usr/bin/env bash
set -eo pipefail

dotfiles_dir=$(realpath $(dirname $0))
source=$(realpath $1)
destination=${HOME}${source/$dotfiles_dir/}

if [ -f ${source} ]; then
	ln -sf ${source} ${destination}
elif [ -f ${destination} ]; then
    mv ${destination} ${source}
	ln -sf ${source} ${destination}
fi
